### ISSUE TITLE
Properties on interfaces should have documentation 

### ISSUE THREAD

**Issue by zahra-audacia** [audaciaconsulting/Audacia.DataAccess#2]
I think the interfaces such as IRowVersionable, should have documentation so that in my project I can use inheritdoc on the property so I dont have a warning saying that the element needs to be documented. Would just be a nice to have.

**Comment by richardb355** [comment]
Resolved in [this PR](https://github.com/audaciaconsulting/Audacia.DataAccess/pull/3) that addressed code analysis warnings.
